language: 
  - php

php:
  - 5.4

services:
# - memcached

before_install:

  - ./cphalcon/unit-tests/ci/install_prereqs.sh

install:
 - (cd cphalcon; composer --prefer-source install)

before_script:
#- git clone -q https://github.com/phalcon/cphalcon.git
# - (cd cphalcon; git submodule update; cd build; sudo ./install && phpenv config-add ../../tests/phalcon.ini)
#  - yum install php-devel
  - sudo apt-get -qq install php5-dev
  - (cd cphalcon/build; sudo ./travis-install && phpenv config-add ../../config/php.d/phalcon.ini)
# - wget http://getcomposer.org/composer.phar
# - php composer.phar install

script: (cd cphalcon/php-tests/tests; phpunit --debug)
